---

modifyingUnitClasses:
  - id: commander_ragna
    replace:
        loadCapacity: 7
    add:
        verbs:
            - pick_up
            - drink_g_pot
            - drink_h_pot
            - dimensional_door
            - buy_artifacts

...
